version: "3.1"
services:
  dotnet:
    container_name: Biopark
    build: .
    ports:
      - "5000:5000"
    networks:
      biopark:
        ipv4_address: 192.168.150.2
  mysql:
    container_name: Mysql
    image: 'mysql:8.0'
    environment:
      MYSQL_DATABASE: 'Biopark'
      MYSQL_USER: 'user'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: 'root_pwd'
    command:
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_bin
      - --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    restart: 'on-failure'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      biopark:
        ipv4_address: 192.168.150.3
  SGBD:
    container_name: Biopark_phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 8010:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root_pwd'
    networks:
      biopark:
        ipv4_address: 192.168.150.4
networks:
  biopark:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.150.0/24
volumes:
  db:
    driver: local
  persistent: