// <auto-generated />
using System;
using DesafioBiopark;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DesafioBiopark.Migrations
{
    [DbContext(typeof(BioparkContext))]
    partial class BioparkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb3_bin")
                .HasAnnotation("ProductVersion", "8.0.0-preview.1.23111.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb3");

            modelBuilder.Entity("DesafioBiopark.Model.Migrations.ApartamentosMigration", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool?>("alugado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("andar")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("edificiosId")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("edificiosId");

                    b.ToTable("Apartamentos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            alugado = false,
                            andar = 1,
                            createdAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(6935),
                            edificiosId = 1,
                            isActive = true,
                            numero = 101,
                            updatedAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(7242)
                        },
                        new
                        {
                            id = 2,
                            alugado = false,
                            andar = 1,
                            createdAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(7758),
                            edificiosId = 1,
                            isActive = true,
                            numero = 102,
                            updatedAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(7763)
                        },
                        new
                        {
                            id = 3,
                            alugado = false,
                            andar = 2,
                            createdAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(7766),
                            edificiosId = 1,
                            isActive = true,
                            numero = 201,
                            updatedAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(7767)
                        },
                        new
                        {
                            id = 4,
                            alugado = false,
                            andar = 2,
                            createdAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(7769),
                            edificiosId = 1,
                            isActive = true,
                            numero = 202,
                            updatedAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(7771)
                        },
                        new
                        {
                            id = 5,
                            alugado = false,
                            andar = 3,
                            createdAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(7773),
                            edificiosId = 1,
                            isActive = true,
                            numero = 301,
                            updatedAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(7774)
                        },
                        new
                        {
                            id = 6,
                            alugado = false,
                            andar = 3,
                            createdAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(7780),
                            edificiosId = 1,
                            isActive = true,
                            numero = 302,
                            updatedAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(7782)
                        },
                        new
                        {
                            id = 7,
                            alugado = false,
                            andar = 4,
                            createdAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(7784),
                            edificiosId = 1,
                            isActive = true,
                            numero = 401,
                            updatedAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(7785)
                        },
                        new
                        {
                            id = 8,
                            alugado = false,
                            andar = 4,
                            createdAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(7787),
                            edificiosId = 1,
                            isActive = true,
                            numero = 402,
                            updatedAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(7788)
                        });
                });

            modelBuilder.Entity("DesafioBiopark.Model.Migrations.ContratoMigration", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("apartamentoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("locatarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("valorAluguelMen")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.HasIndex("apartamentoId");

                    b.HasIndex("locatarioId");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("DesafioBiopark.Model.Migrations.EdificiosMigration", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("locadora")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("Edificios");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdAt = new DateTime(2023, 3, 5, 20, 52, 59, 829, DateTimeKind.Local).AddTicks(3808),
                            isActive = true,
                            locadora = "Biopark",
                            nome = "Edificio primavera",
                            updatedAt = new DateTime(2023, 3, 5, 20, 52, 59, 852, DateTimeKind.Local).AddTicks(5225)
                        });
                });

            modelBuilder.Entity("DesafioBiopark.Model.Migrations.LocatariosMigration", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("dataNasc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("Locatarios");

                    b.HasData(
                        new
                        {
                            id = 1,
                            createdAt = new DateTime(2023, 3, 5, 20, 52, 59, 853, DateTimeKind.Local).AddTicks(9106),
                            dataNasc = new DateTime(1944, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            nome = "Alexandre Levi Renato Baptista",
                            updatedAt = new DateTime(2023, 3, 5, 20, 52, 59, 853, DateTimeKind.Local).AddTicks(9407)
                        },
                        new
                        {
                            id = 2,
                            createdAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(89),
                            dataNasc = new DateTime(1944, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            nome = "Alexandre Levi Renato Baptista",
                            updatedAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(96)
                        },
                        new
                        {
                            id = 3,
                            createdAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(98),
                            dataNasc = new DateTime(2002, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            nome = "Liz Sônia Bernardes",
                            updatedAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(100)
                        },
                        new
                        {
                            id = 4,
                            createdAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(102),
                            dataNasc = new DateTime(1952, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            nome = "Lucas Pietro Noah Moura",
                            updatedAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(103)
                        },
                        new
                        {
                            id = 5,
                            createdAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(105),
                            dataNasc = new DateTime(1962, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            nome = "Elaine Natália Renata Souza",
                            updatedAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(107)
                        },
                        new
                        {
                            id = 6,
                            createdAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(120),
                            dataNasc = new DateTime(1945, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            nome = "Elisa Bianca Porto",
                            updatedAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(121)
                        },
                        new
                        {
                            id = 7,
                            createdAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(123),
                            dataNasc = new DateTime(1978, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            nome = "Francisca Isabelly Débora Rocha",
                            updatedAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(124)
                        },
                        new
                        {
                            id = 8,
                            createdAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(126),
                            dataNasc = new DateTime(1989, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            nome = "Alexandre Bryan Nogueira",
                            updatedAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(127)
                        },
                        new
                        {
                            id = 9,
                            createdAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(129),
                            dataNasc = new DateTime(1982, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            nome = "Nicole Analu Sarah Brito",
                            updatedAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(130)
                        },
                        new
                        {
                            id = 10,
                            createdAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(134),
                            dataNasc = new DateTime(1954, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            nome = "Daiane Sabrina da Rosa",
                            updatedAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(135)
                        },
                        new
                        {
                            id = 11,
                            createdAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(137),
                            dataNasc = new DateTime(1978, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            isActive = true,
                            nome = "Benício Manuel Lima",
                            updatedAt = new DateTime(2023, 3, 5, 20, 52, 59, 854, DateTimeKind.Local).AddTicks(138)
                        });
                });

            modelBuilder.Entity("DesafioBiopark.Model.Migrations.ApartamentosMigration", b =>
                {
                    b.HasOne("DesafioBiopark.Model.Migrations.EdificiosMigration", "edificios")
                        .WithMany()
                        .HasForeignKey("edificiosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("edificios");
                });

            modelBuilder.Entity("DesafioBiopark.Model.Migrations.ContratoMigration", b =>
                {
                    b.HasOne("DesafioBiopark.Model.Migrations.ApartamentosMigration", "apartamento")
                        .WithMany()
                        .HasForeignKey("apartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesafioBiopark.Model.Migrations.LocatariosMigration", "locatario")
                        .WithMany()
                        .HasForeignKey("locatarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("apartamento");

                    b.Navigation("locatario");
                });
#pragma warning restore 612, 618
        }
    }
}
